# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

configuration_file_path = File.join(__dir__, '..', 'config.xcconfig')
configuration = Xcodeproj::Config.new(configuration_file_path)

changelog_file_path = File.join(__dir__, '..', '..', 'changelog.txt')
changelog = File.exist?(changelog_file_path) ? File.read(changelog_file_path) : nil

def print_changelog(changelog)
  if changelog
    puts "\n\n-- Changelog ---------------------------\n#{changelog}\n----------------------------------------\n"
  else
    puts "\n\n-- Changelog ---------------------------\nNO CHANGELOG FILE FOUND\n----------------------------------------\n"
  end

  sleep 4
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :nightly do
    print_changelog(changelog)

    app_store_connect_api_key(
      key_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_filepath: configuration.attributes['APP_STORE_CONNECT_API_KEY_FILE_PATH'],
    )
    # Not sure if get_certificates and get_provisioning_profile is needed here
    # get_certificates(
    #   team_id: configuration.attributes['DEVELOPMENT_TEAM'],
    # )
    # get_provisioning_profile(
    #   app_identifier: configuration.attributes['PRODUCT_BUNDLE_IDENTIFIER_NIGHTLY'],
    #   team_id: configuration.attributes['DEVELOPMENT_TEAM'],
    # )

    build_app(workspace: "Inventory.xcworkspace", scheme: "Inventory (Nightly)")

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: changelog,
    )
  end

  lane :release do
    print_changelog(changelog)

    app_store_connect_api_key(
      key_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_filepath: configuration.attributes['APP_STORE_CONNECT_API_KEY_FILE_PATH'],
    )
    # Not sure if get_certificates and get_provisioning_profile is needed here
    # get_certificates(
    #   team_id: configuration.attributes['DEVELOPMENT_TEAM'],
    # )
    # get_provisioning_profile(
    #   app_identifier: configuration.attributes['PRODUCT_BUNDLE_IDENTIFIER_RELEASE'],
    #   team_id: configuration.attributes['DEVELOPMENT_TEAM'],
    # )

    build_app(workspace: "Inventory.xcworkspace", scheme: "Inventory")

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: changelog,
    )
  end
end
