# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

configuration_file_path = File.join(__dir__, '..', 'config.xcconfig')
configuration = Xcodeproj::Config.new(configuration_file_path)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :nightly do
    build_app(workspace: "Inventory.xcworkspace", scheme: "Inventory (Nightly)")
    changelog_from_git_commits
    app_store_connect_api_key(
      key_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: configuration.attributes['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_filepath: configuration.attributes['APP_STORE_CONNECT_API_KEY_FILE_PATH'],
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
